display toaster upon profile form save success and error
onlydustxyz/marketplace pull request #540
Opened 2023-01-18 17:56 UTC by AnthonyBuisset

closes E-200

2023-01-18 19:11 UTC, Bernardstanislas approved these changes

2023-01-18 19:11 UTC, Bernardstanislas commented on frontend/src/hooks/useToaster/useToaster.test.tsx
> +    result.current.showToaster("Message", { duration: 100 });
You can even put realistic values here, and use https://vitest.dev/guide/mocking.html#timers – be ready for 🤯

2023-01-18 19:11 UTC, Bernardstanislas commented on tailwind.config.js
> +        "od-gradient":
can you find a more explicit name? Something like "colorful-gradient"?

2023-01-18 19:11 UTC, Bernardstanislas commented on frontend/src/translations/en.json
> +    "errorOccured": "An error just occurred, please try again. Contact us at contact@onlydust.xyz if the problem persists",
Let me create the alias right now 😆

2023-01-18 19:38 UTC, oscarwroche requested changes

2023-01-19 10:56 UTC, AnthonyBuisset commented on frontend/src/hooks/useToaster/useToaster.test.tsx
> +    result.current.showToaster("Message", { duration: 100 });
I will do it in a dedicated PR as I am facing issues with those

2023-01-19 10:56 UTC, AnthonyBuisset commented on frontend/src/pages/Profile/components/ProfileForm.tsx
> +      ignoreGraphQLErrors: true, // tell ApolloWrapper to ignore the errors
done @oscarwroche

2023-01-19 13:20 UTC, oscarwroche approved these changes

2023-01-19 13:28 UTC, merged