Display PR link in My contributions table
onlydustxyz/marketplace pull request #568
Opened 2023-01-24 10:36 UTC by ofux

- 💄 Display PR link in My contributions table

2023-01-24 13:47 UTC, oscarwroche requested changes

2023-01-24 13:47 UTC, oscarwroche commented on frontend/src/components/PayoutTable/GithubPRLink/index.tsx
> +export default function GithubPRLink({ link, className }: LinkProps) {
**Standard: [*Tailwind class name*](https://www.notion.so/onlydust/Tailwind-class-name-e9762becd8324d959ca9127a7205914a#8a86b0a416aa4984bc4607a0d14d126d)**
Nitpicking here, but it's better to have an explicit class name (like 'variant') rather than a generic className prop

2023-01-24 21:11 UTC, AnthonyBuisset approved these changes

2023-01-24 21:11 UTC, AnthonyBuisset commented on frontend/src/components/PayoutTable/GithubPRLink/GithubPRLink.test.tsx
> +describe.each([
😍

2023-01-24 21:11 UTC, AnthonyBuisset commented on frontend/src/components/PayoutTable/GithubPRLink/index.tsx
> +      <ExternalLinkLine className="flex text-fuchsia-700 invisible group-hover/github-pr-link:visible" />
Color should be `spacePurple-500` but we can track it in E-109

2023-01-24 21:13 UTC, AnthonyBuisset commented on frontend/src/components/PayoutTable/GithubPRLink/index.tsx
> +  Grey = "text-neutral-400",
text color is `spaceBlue-200` according to FIgma

2023-01-24 21:14 UTC, AnthonyBuisset commented on frontend/src/components/PayoutTable/GithubPRLink/index.tsx
> +    <div className="group/github-pr-link flex flex-row gap-2 w-fit items-center hover:cursor-pointer">
`gap-1` according to Figma

2023-01-25 10:07 UTC, oscarwroche approved these changes

2023-01-25 10:07 UTC, merged