E 369
onlydustxyz/marketplace pull request #674
Opened 2023-02-10 14:02 UTC by tdelabro

2023-02-10 14:18 UTC, AnthonyBuisset requested changes
LGTM

2023-02-10 14:19 UTC, AnthonyBuisset approved these changes

2023-02-10 16:45 UTC, Bernardstanislas requested changes

2023-02-10 16:45 UTC, Bernardstanislas commented on backend/api/src/presentation/http/dto/ethereum.rs
> +		match value.r#type {
I think this is not flexible enough, we want to have a single string field that is checked to be either a valid ethereum address, or an ens.
The tools calling the mutation don't know how to distinguish one from the other, so we cannot expect them to provide a `type`

2023-02-10 16:49 UTC, tdelabro commented on backend/api/src/presentation/http/dto/ethereum.rs
> +		match value.r#type {
I cannot really do that without moving in the mutation itself some logic that belongs to the GraphQl layer.
And without removing the strong types we have in this API.
I would rather have the front adapt. It can detect that, either by providing the users with two forms, or by doing a first parse of the user input

2023-02-13 09:37 UTC, Bernardstanislas approved these changes

2023-02-13 09:37 UTC, merged