feat(db): add sponsors and projects_sponsors table
onlydustxyz/marketplace pull request #692
Opened 2023-02-14 21:45 UTC by tdelabro

2023-02-15 10:57 UTC, Bernardstanislas requested changes

2023-02-15 10:57 UTC, Bernardstanislas commented on migrations/2023-02-14-140832_add-sponsors/up.sql
> +    project_id UUID REFERENCES projects(id),
can you put a cascade delete? Because what will happen, is that when we refresh the projection of a project aggregate, the `project` db model will be deleted, and without cascading it will fail because of this foreign key :)

2023-02-16 09:36 UTC, tdelabro commented on migrations/2023-02-14-140832_add-sponsors/up.sql
> +    project_id UUID REFERENCES projects(id),
done

2023-02-16 09:39 UTC, Bernardstanislas approved these changes

2023-02-16 09:39 UTC, merged