feat: remplace project description by short and long descriptions
onlydustxyz/marketplace pull request #702
Opened 2023-02-16 13:55 UTC by tdelabro

2023-02-16 17:01 UTC, ofux requested changes
Just add a bit of input validation (see comment) and fix e2e tests :)

2023-02-16 17:01 UTC, ofux commented on backend/api/src/application/project/create.rs
> +		long_description: String,
`NonEmptyTrimmedString` would be better here to validate inputs

2023-02-17 10:26 UTC, tdelabro commented on backend/api/src/application/project/create.rs
> +		long_description: String,
done

2023-02-17 10:41 UTC, ofux approved these changes

2023-02-17 10:56 UTC, merged