[B-780] Show a back button on the send payment page
onlydustxyz/marketplace pull request #789
Opened 2023-03-09 11:20 UTC by AnthonyBuisset

closes B-780

2023-03-09 14:50 UTC, ofux approved these changes

2023-03-09 14:50 UTC, ofux commented on frontend/src/components/Button/index.tsx
> +          "p-1": size === ButtonSize.Xs && iconOnly,
Wouldn't it work like this? 👇 

```ts
!iconOnly && {
          "px-6 py-4": size === ButtonSize.Lg,
          "px-4 py-1.5": size === (ButtonSize.LgLowHeight || ButtonSize.Md),
          "px-4 py-2": size === ButtonSize.Sm,
          "px-2 py-1": size === ButtonSize.Xs,
},
iconOnly && {
          "p-4": size === ButtonSize.Lg,
          "p-3.5": size === (ButtonSize.LgLowHeight || ButtonSize.Md),
          "p-2": size === ButtonSize.Sm,
          "p-1": size === ButtonSize.Xs,
}
```

2023-03-09 15:29 UTC, oscarwroche commented
![Screenshot 2023-03-09 at 16 27 46](https://user-images.githubusercontent.com/21149076/224072111-9df14e46-f1fc-46b5-92fc-4e98140253f1.png)

The font size is wrong (should be 24px) and there is insufficient padding below "Send payment"

2023-03-09 15:30 UTC, oscarwroche commented
The font size for "All projects" should be 16px

2023-03-09 15:30 UTC, oscarwroche requested changes
See style comments

2023-03-10 13:39 UTC, oscarwroche approved these changes

2023-03-10 13:39 UTC, merged