🗃️ create crm_github_repos table
onlydustxyz/marketplace pull request #850
Opened 2023-03-31 09:24 UTC by ofux

2023-03-31 09:26 UTC, AnthonyBuisset approved these changes

2023-04-03 15:09 UTC, AnthonyBuisset requested changes

2023-04-03 15:09 UTC, AnthonyBuisset commented on backend/event-listeners/src/domain/projectors/project.rs
> +	fn remove_orphan_github_repo_details(&self, github_repo_id: &GithubRepositoryId) -> Result<()> {
❤️

2023-04-03 15:23 UTC, ofux commented on backend/common/domain/src/project/aggregate.rs
> +				self.github_repos.insert(*github_repo_id);
BTW, I tested the refresh on my local env. And this makes me think: we could (should) include a simple e2e tests that just triggers a complete refresh and check it doesn't return an error.

2023-04-03 15:53 UTC, merged